version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: playnow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: playnow
    ports:
      - "5432:5432"
    volumes:
      - playnow_data:/var/lib/postgresql/data
    networks:
      - playnow-network

  backend:
    build: ./backend
    container_name: playnow-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: playnow
      DB_PORT: 5432
      JWT_SECRET: supersecreto123
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: nodemon --legacy-watch server.js
    working_dir: /app
    networks:
      - playnow-network

volumes:
  playnow_data:

networks:
  playnow-network:
